import type { Metadata } from 'next';
import '@/styles/globals.css';
import type { ChildrenProps } from '@/types';
import Footer from '@/components/Footer/Footer';
import Header from '@/components/Header/Header';

export const metadata: Metadata = {
  title: 'Story',
  description: 'Generated by create next app',
};

export default async function Layout({ children }: ChildrenProps) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
